FAÇA UM JOGO ESTILO 21 ONDE O USUARIO PODE PEDIR UMA CARTA BAIXA, MEDIA OU ALTA.
A CADA RODADA UM JOGADOR DIFERENTE (NUMERO DA RODADA) VAI JOGAR. O JOGO TERMINA QUANDO O USUARIO SOLICITAR E/OU UM JOGADOR ACERTAR EXATAMENTE OS 21 PONTOS.
 QUANDO O USUARIO ESCOLHER UMA CARTA
    BAIXA - UMA CARTA ENTRE 1-5 SERÁ SORTEADA.
    MEDIA - UMA CARTA ENTRE 6-9
    ALTA - UMA CARTA ENTRE 10-13

    O USUARIO PODE ESCOLHAR
        PARAR
        BAIXA
        MEDIA
        ALTA

    A CADA RODADA, PERGUNTAR SE QUER CONTINUAR JOGANDO.

    NO FINAL INDICAR QUAL O JOGADOR (RODADA, FEZ MAIS PONTOS)